### ISSUE TITLE
How to train on non squered images? I see you trained on 150x1920 images, but in the paper it says that they pass only 256x256 images.

### ISSUE THREAD

**Issue by karollpanagi3** [aggelos-michael-papadopoulos/Mobile-ViT-impelmentation-and-training-on-Tensorlow-and-Pytorch#1]

**Comment by aggelos-michael-papadopoulos** [comment]
Yes, the paper does pass 256x256. But if you want to train on non-squered images in mobile-ViT you have to pay attention to the below 2 equations:

1) To know the outpout size of your CNN:

![2022-11-20 23_31_09-Προβολή παρουσίασης PowerPoint -  MobileViT presentation](https://user-images.githubusercontent.com/65830412/202927238-c3b63f0a-629b-4d3f-ae9b-2f43cc2899e0.png)

2) To have an integer number of patches (here patch size is 2x2), if you want it to pass through the transformer:

![2022-11-20 23_31_18-Προβολή παρουσίασης PowerPoint -  MobileViT presentation](https://user-images.githubusercontent.com/65830412/202927252-79d9d236-3cc8-4c34-9b7e-a075480baa6f.png)

So taking into consideration the above 2 equations, we can see that mobileViT satisfies them through the entire architecture if we have an image of 150x1920 as we can see in the image below:

![2022-11-20 23_31_28-Προβολή παρουσίασης PowerPoint -  MobileViT presentation](https://user-images.githubusercontent.com/65830412/202927440-14a21b06-1232-4993-9e1d-8d6d98f5415a.png)
